import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';

const initialState = {
    place: {

    },
};

export const workplaceSlice = createSlice({
    name: 'workplace',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        doGetWorkplace: (state, action) => {
            state.place = action.payload;
        },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {

    },
});

export const { doGetWorkplace } = workplaceSlice.actions;



export default workplaceSlice.reducer;
