import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';

const initialState = {

    user: {
    },
};

export const lecturerSlice = createSlice({
    name: 'lecturer',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {

        doGetLecturerInfoAction: (state, action) => {
            state.user = action.payload;
        },

        doClearLecturerInfo: (state, action) => {
            state.user = ''
        },


    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {

    },
});

export const { doGetLecturerInfoAction, doClearLecturerInfo } = lecturerSlice.actions;



export default lecturerSlice.reducer;
