import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';

const initialState = {

    user: {
    },
};

export const studentSlice = createSlice({
    name: 'student',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {

        doGetStudentInfoAction: (state, action) => {
            state.user = action.payload;
        },

        doClearStudentInfo: (state, action) => {
            state.user = ''
        },


    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {

    },
});

export const { doGetStudentInfoAction, doClearStudentInfo } = studentSlice.actions;



export default studentSlice.reducer;
